"""add fields to households

Revision ID: 48d02a68a0f7
Revises: 6c1daf6e1a75
Create Date: 2025-08-14 14:26:08.718047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d02a68a0f7'
down_revision = '6c1daf6e1a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('monthly_income', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('toilet_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('head_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'residents', ['head_id'], ['id'])
        batch_op.drop_column('head_name')
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=80), nullable=False))
        batch_op.drop_column('full_name')

    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.create_unique_constraint('_resident_uc', ['first_name', 'last_name', 'birth_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_constraint('_resident_uc', type_='unique')

    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('head_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('head_id')
        batch_op.drop_column('remarks')
        batch_op.drop_column('toilet_type')
        batch_op.drop_column('monthly_income')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
