"""Add new fields to Resident model

Revision ID: 6c1daf6e1a75
Revises: e7821b0e3cb8
Create Date: 2025-08-12 16:55:11.703125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c1daf6e1a75'
down_revision = 'e7821b0e3cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('place_of_birth', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('civil_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('purok', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('voters_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('identified_as', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('occupation', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('citizenship', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('citizenship')
        batch_op.drop_column('occupation')
        batch_op.drop_column('identified_as')
        batch_op.drop_column('voters_status')
        batch_op.drop_column('purok')
        batch_op.drop_column('civil_status')
        batch_op.drop_column('place_of_birth')
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
