"""add missing fields to models

Revision ID: e7821b0e3cb8
Revises: 
Create Date: 2025-08-12 11:52:48.684831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7821b0e3cb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blotters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('case_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('respondent_name', sa.String(length=120), nullable=True))

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))

    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residents', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('households', schema=None) as batch_op:
        batch_op.drop_column('contact_number')

    with op.batch_alter_table('blotters', schema=None) as batch_op:
        batch_op.drop_column('respondent_name')
        batch_op.drop_column('case_type')

    # ### end Alembic commands ###
